apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels: { app: api }
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: 3001
          env:
            - name: REDIS_URL
              value: {{ .Values.api.env.REDIS_URL | quote }}
            - name: SQS_QUEUE_URL
              value: {{ .Values.api.env.SQS_QUEUE_URL | quote }}
            - name: SQS_DLQ_URL
              value: {{ .Values.api.env.SQS_DLQ_URL | quote }}
            - name: AWS_REGION
              value: {{ .Values.api.env.AWS_REGION | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.secretRef }}
                  key: DATABASE_URL
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.secretRef }}
                  key: AUTH_SECRET
            - name: APP_AES_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.secretRef }}
                  key: APP_AES_KEY
