{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  {{- $store := .Values.externalSecrets.clusterSecretStoreName | default (ternary "aws-secretsmanager" "aws-ssm" (eq .Values.externalSecrets.store "secretsmanager")) }}
  secretStoreRef:
    kind: {{ .Values.externalSecrets.storeKind | default "ClusterSecretStore" }}
    name: {{ $store }}
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
{{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
{{- end }}
{{- end }}
