{{- if eq .Values.exposure.type "nlb-web" }}
apiVersion: v1
kind: Service
metadata:
  name: web-nlb
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    {{- if .Values.externalDNS.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDNS.hostname | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  selector: { app: web }
  ports:
    - name: http
      port: 80
      targetPort: 3000
{{- end }}

