apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels: { app: api }
  template:
    metadata:
      labels: { app: api }
    spec:
      containers:
        - name: api
          image: api
          ports: [{ containerPort: 3001 }]
          env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: app-secrets, key: DATABASE_URL } }
            - name: AUTH_SECRET
              valueFrom: { secretKeyRef: { name: app-secrets, key: AUTH_SECRET } }
            - name: APP_AES_KEY
              valueFrom: { secretKeyRef: { name: app-secrets, key: APP_AES_KEY } }
            - name: REDIS_URL
              value: redis://redis:6379
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
