apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
        - name: web
          image: web
          ports: [{ containerPort: 3000 }]
          env:
            - name: NEXT_PUBLIC_API_BASE
              value: https://REPLACE_WITH_DOMAIN
            - name: API_BASE
              value: http://api:3001
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "500m", memory: "512Mi" }
