apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-mailer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_REPO_URL
    targetRevision: REPLACE_TARGET_REVISION
    path: argo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
