apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avnz-portal-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_REPO_URL
    targetRevision: main
    path: charts/avnz-portal
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: avnz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

