apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-stores
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_REPO_URL
    targetRevision: main
    path: k8s/eso
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

