name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint web/api
        run: bash scripts/lint.sh

  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start DB
        run: docker compose up -d db
      - name: Build and start services
        run: docker compose up -d --build api ai web
      - name: Health check
        run: bash scripts/health-check.sh
      - name: Smoke tests
        run: bash scripts/smoke-test.sh
      - name: Walkthrough
        run: bash scripts/walkthrough.sh
      - name: Inspect recent web logs for errors (non-fatal)
        run: |
          docker compose logs --since 15m web | sed -n '1,200p'
      - name: Inspect recent api logs for errors (non-fatal)
        run: |
          docker compose logs --since 15m api | sed -n '1,200p'

